---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timerec-api
  labels:
    app.kubernetes.io/name: timerec
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: timerec
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: timerec
    spec:
      containers:
      - name: timerec-server
        image: ghcr.io/thomasbuchinger/timerec:main
        imagePullPolicy: Always
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        args:
          - "/timerec-server"
          - "--config"
          - "/conf/timerec-config.yaml"
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: "10Mi"
            cpu: "1m"
          limits:
            memory: "20Mi"
            cpu: "10m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 60
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          failureThreshold: 3
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 60
        volumeMounts:
        - name: config
          mountPath: /conf/
      serviceAccountName: timerec-sa
      volumes:
        - name: config
          configMap:
            name: timerec-cm

---
apiVersion: v1
kind: Service
metadata:
  name: timerec
spec:
  selector:
      app.kubernetes.io/name: timerec
  ports:
  - name: http
    port: 8080
    targetPort: http
