---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: timerec-server
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: timerec-server
subjects:
  - kind: ServiceAccount
    name: timerec-sa
roleRef:
  kind: Role
  name: timerec-server
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: timerec-sa